//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class convert_bbcode_mediatag
    {
        public int mediatag_id { get; set; }
        public string mediatag_name { get; set; }
        public string mediatag_match { get; set; }
        public string mediatag_replace { get; set; }
        public short mediatag_position { get; set; }
    }
}
