//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class convert_link
    {
        public long link_id { get; set; }
        public int ipb_id { get; set; }
        public string foreign_id { get; set; }
        public string type { get; set; }
        public bool duplicate { get; set; }
        public int app { get; set; }
    }
}
