//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class convert_custom_bbcode
    {
        public int bbcode_id { get; set; }
        public string bbcode_title { get; set; }
        public string bbcode_desc { get; set; }
        public string bbcode_tag { get; set; }
        public string bbcode_replace { get; set; }
        public bool bbcode_useoption { get; set; }
        public string bbcode_example { get; set; }
        public int bbcode_switch_option { get; set; }
        public string bbcode_menu_option_text { get; set; }
        public string bbcode_menu_content_text { get; set; }
        public bool bbcode_single_tag { get; set; }
        public string bbcode_groups { get; set; }
        public string bbcode_sections { get; set; }
        public string bbcode_php_plugin { get; set; }
        public bool bbcode_no_parsing { get; set; }
        public bool bbcode_protected { get; set; }
        public string bbcode_aliases { get; set; }
        public bool bbcode_optional_option { get; set; }
        public string bbcode_image { get; set; }
        public string bbcode_app { get; set; }
        public string bbcode_custom_regex { get; set; }
    }
}
