//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class convert_logs
    {
        public decimal log_id { get; set; }
        public string log_message { get; set; }
        public long log_app { get; set; }
        public string log_method { get; set; }
        public bool log_severity { get; set; }
        public string log_item_id { get; set; }
        public int log_time { get; set; }
    }
}
