//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_widgets
    {
        public decimal id { get; set; }
        public string key { get; set; }
        public string app { get; set; }
        public string plugin { get; set; }
        public string @class { get; set; }
        public string caches { get; set; }
        public string restrict { get; set; }
        public string default_area { get; set; }
        public bool allow_reuse { get; set; }
        public string menu_style { get; set; }
        public bool embeddable { get; set; }
    }
}
