//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_follow
    {
        public string follow_id { get; set; }
        public string follow_app { get; set; }
        public string follow_area { get; set; }
        public decimal follow_rel_id { get; set; }
        public decimal follow_member_id { get; set; }
        public int follow_is_anon { get; set; }
        public long follow_added { get; set; }
        public int follow_notify_do { get; set; }
        public string follow_notify_meta { get; set; }
        public string follow_notify_freq { get; set; }
        public long follow_notify_sent { get; set; }
        public sbyte follow_visible { get; set; }
        public Nullable<decimal> follow_index_id { get; set; }
    }
}
