//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_error_logs
    {
        public int log_id { get; set; }
        public decimal log_member { get; set; }
        public int log_date { get; set; }
        public string log_error { get; set; }
        public string log_error_code { get; set; }
        public string log_ip_address { get; set; }
        public string log_request_uri { get; set; }
    }
}
