//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_menu
    {
        public decimal id { get; set; }
        public string app { get; set; }
        public string extension { get; set; }
        public string config { get; set; }
        public long position { get; set; }
        public Nullable<long> parent { get; set; }
        public string permissions { get; set; }
        public bool is_menu_child { get; set; }
    }
}
