//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public core_members()
        {
            this.zzukbot_migrated_users = new HashSet<zzukbot_migrated_users>();
        }
    
        public decimal member_id { get; set; }
        public string name { get; set; }
        public short member_group_id { get; set; }
        public string email { get; set; }
        public int joined { get; set; }
        public string ip_address { get; set; }
        public Nullable<short> skin { get; set; }
        public Nullable<int> warn_level { get; set; }
        public int warn_lastwarn { get; set; }
        public Nullable<int> language { get; set; }
        public int restrict_post { get; set; }
        public Nullable<int> bday_day { get; set; }
        public Nullable<int> bday_month { get; set; }
        public Nullable<int> bday_year { get; set; }
        public int msg_count_new { get; set; }
        public int msg_count_total { get; set; }
        public int msg_count_reset { get; set; }
        public int msg_show_notification { get; set; }
        public Nullable<int> last_visit { get; set; }
        public Nullable<int> last_activity { get; set; }
        public int mod_posts { get; set; }
        public string auto_track { get; set; }
        public Nullable<int> temp_ban { get; set; }
        public string mgroup_others { get; set; }
        public string member_login_key { get; set; }
        public int member_login_key_expire { get; set; }
        public string members_seo_name { get; set; }
        public string members_cache { get; set; }
        public string failed_logins { get; set; }
        public short failed_login_count { get; set; }
        public long members_profile_views { get; set; }
        public string members_pass_hash { get; set; }
        public string members_pass_salt { get; set; }
        public long members_bitoptions { get; set; }
        public decimal fb_uid { get; set; }
        public string members_day_posts { get; set; }
        public string live_id { get; set; }
        public string twitter_id { get; set; }
        public string twitter_token { get; set; }
        public string twitter_secret { get; set; }
        public int notification_cnt { get; set; }
        public string fb_token { get; set; }
        public int ipsconnect_id { get; set; }
        public string google_id { get; set; }
        public string linkedin_id { get; set; }
        public string pp_last_visitors { get; set; }
        public string pp_main_photo { get; set; }
        public Nullable<int> pp_main_width { get; set; }
        public Nullable<int> pp_main_height { get; set; }
        public string pp_thumb_photo { get; set; }
        public Nullable<int> pp_thumb_width { get; set; }
        public Nullable<int> pp_thumb_height { get; set; }
        public Nullable<int> pp_setting_count_comments { get; set; }
        public Nullable<int> pp_reputation_points { get; set; }
        public string pp_gravatar { get; set; }
        public string pp_photo_type { get; set; }
        public string signature { get; set; }
        public string pconversation_filters { get; set; }
        public string fb_photo { get; set; }
        public string fb_photo_thumb { get; set; }
        public Nullable<int> fb_bwoptions { get; set; }
        public string tc_last_sid_import { get; set; }
        public string tc_photo { get; set; }
        public Nullable<int> tc_bwoptions { get; set; }
        public string pp_customization { get; set; }
        public string timezone { get; set; }
        public string pp_cover_photo { get; set; }
        public string profilesync { get; set; }
        public int profilesync_lastsync { get; set; }
        public string google_token { get; set; }
        public string linkedin_token { get; set; }
        public string live_token { get; set; }
        public Nullable<bool> allow_admin_mails { get; set; }
        public long members_bitoptions2 { get; set; }
        public string create_menu { get; set; }
        public string ipsconnect_revalidate_url { get; set; }
        public bool members_disable_pm { get; set; }
        public Nullable<long> marked_site_read { get; set; }
        public int pp_cover_offset { get; set; }
        public Nullable<short> acp_skin { get; set; }
        public Nullable<int> acp_language { get; set; }
        public string member_title { get; set; }
        public int member_posts { get; set; }
        public Nullable<int> member_last_post { get; set; }
        public string member_streams { get; set; }
        public Nullable<int> photo_last_update { get; set; }
        public string mfa_details { get; set; }
        public Nullable<int> failed_mfa_attempts { get; set; }
        public string cm_credits { get; set; }
        public Nullable<bool> cm_no_sev { get; set; }
        public Nullable<short> cm_return_group { get; set; }
        public string conv_password { get; set; }
        public string conv_password_extra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zzukbot_migrated_users> zzukbot_migrated_users { get; set; }
    }
}
