//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_sys_lang
    {
        public int lang_id { get; set; }
        public string lang_short { get; set; }
        public string lang_title { get; set; }
        public bool lang_default { get; set; }
        public bool lang_isrtl { get; set; }
        public bool lang_protected { get; set; }
        public Nullable<int> lang_order { get; set; }
        public bool lang_enabled { get; set; }
    }
}
