//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_message_topics
    {
        public int mt_id { get; set; }
        public int mt_date { get; set; }
        public string mt_title { get; set; }
        public short mt_hasattach { get; set; }
        public int mt_starter_id { get; set; }
        public int mt_start_time { get; set; }
        public int mt_last_post_time { get; set; }
        public int mt_to_count { get; set; }
        public decimal mt_to_member_id { get; set; }
        public int mt_replies { get; set; }
        public int mt_first_msg_id { get; set; }
        public int mt_is_draft { get; set; }
        public int mt_is_deleted { get; set; }
        public int mt_is_system { get; set; }
    }
}
