//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_members_warn_actions
    {
        public long wa_id { get; set; }
        public Nullable<int> wa_points { get; set; }
        public Nullable<int> wa_mq { get; set; }
        public string wa_mq_unit { get; set; }
        public Nullable<int> wa_rpa { get; set; }
        public string wa_rpa_unit { get; set; }
        public Nullable<int> wa_suspend { get; set; }
        public string wa_suspend_unit { get; set; }
        public Nullable<bool> wa_override { get; set; }
    }
}
