//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_dnames_change
    {
        public int dname_id { get; set; }
        public decimal dname_member_id { get; set; }
        public int dname_date { get; set; }
        public string dname_ip_address { get; set; }
        public string dname_previous { get; set; }
        public string dname_current { get; set; }
        public Nullable<bool> dname_discount { get; set; }
    }
}
