//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_log
    {
        public decimal id { get; set; }
        public string exception_class { get; set; }
        public Nullable<long> exception_code { get; set; }
        public string message { get; set; }
        public string backtrace { get; set; }
        public int time { get; set; }
        public string category { get; set; }
        public string url { get; set; }
        public decimal member_id { get; set; }
    }
}
