//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_queue
    {
        public decimal id { get; set; }
        public string data { get; set; }
        public int offset { get; set; }
        public int date { get; set; }
        public string app { get; set; }
        public string key { get; set; }
        public bool priority { get; set; }
    }
}
