//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_ratings
    {
        public decimal id { get; set; }
        public string @class { get; set; }
        public decimal item_id { get; set; }
        public decimal member { get; set; }
        public bool rating { get; set; }
        public string ip { get; set; }
    }
}
