//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_theme_conflict
    {
        public int conflict_id { get; set; }
        public int conflict_set_id { get; set; }
        public int conflict_item_id { get; set; }
        public string conflict_type { get; set; }
        public string conflict_app { get; set; }
        public string conflict_location { get; set; }
        public string conflict_path { get; set; }
        public string conflict_name { get; set; }
        public string conflict_data { get; set; }
        public string conflict_content { get; set; }
        public int conflict_long_version { get; set; }
        public int conflict_date { get; set; }
    }
}
