//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_announcements
    {
        public long announce_id { get; set; }
        public string announce_title { get; set; }
        public string announce_content { get; set; }
        public decimal announce_member_id { get; set; }
        public long announce_views { get; set; }
        public long announce_start { get; set; }
        public long announce_end { get; set; }
        public bool announce_active { get; set; }
        public string announce_seo_title { get; set; }
        public string announce_ids { get; set; }
        public string announce_app { get; set; }
        public string announce_location { get; set; }
        public string announce_permissions { get; set; }
    }
}
