//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_message_topic_user_map
    {
        public int map_id { get; set; }
        public int map_user_id { get; set; }
        public int map_topic_id { get; set; }
        public string map_folder_id { get; set; }
        public int map_read_time { get; set; }
        public int map_user_active { get; set; }
        public int map_user_banned { get; set; }
        public int map_has_unread { get; set; }
        public int map_is_system { get; set; }
        public int map_is_starter { get; set; }
        public int map_left_time { get; set; }
        public int map_ignore_notification { get; set; }
        public int map_last_topic_reply { get; set; }
    }
}
