//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_member_status_replies
    {
        public int reply_id { get; set; }
        public long reply_status_id { get; set; }
        public decimal reply_member_id { get; set; }
        public long reply_date { get; set; }
        public string reply_content { get; set; }
        public bool reply_approved { get; set; }
        public string reply_ip_address { get; set; }
    }
}
