//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_soft_delete_log
    {
        public int sdl_id { get; set; }
        public int sdl_obj_id { get; set; }
        public string sdl_obj_key { get; set; }
        public decimal sdl_obj_member_id { get; set; }
        public int sdl_obj_date { get; set; }
        public string sdl_obj_reason { get; set; }
        public int sdl_locked { get; set; }
    }
}
