//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_leaders
    {
        public decimal leader_id { get; set; }
        public string leader_type { get; set; }
        public long leader_type_id { get; set; }
        public int leader_group_id { get; set; }
        public Nullable<long> leader_position { get; set; }
    }
}
