//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_advertisements
    {
        public long ad_id { get; set; }
        public string ad_location { get; set; }
        public string ad_html { get; set; }
        public string ad_images { get; set; }
        public string ad_link { get; set; }
        public decimal ad_impressions { get; set; }
        public int ad_clicks { get; set; }
        public string ad_exempt { get; set; }
        public sbyte ad_active { get; set; }
        public string ad_html_https { get; set; }
        public int ad_start { get; set; }
        public int ad_end { get; set; }
        public int ad_maximum_value { get; set; }
        public string ad_maximum_unit { get; set; }
        public string ad_additional_settings { get; set; }
        public Nullable<bool> ad_html_https_set { get; set; }
        public Nullable<decimal> ad_member { get; set; }
        public bool ad_new_window { get; set; }
    }
}
