//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_theme_css
    {
        public int css_id { get; set; }
        public int css_set_id { get; set; }
        public int css_updated { get; set; }
        public string css_location { get; set; }
        public string css_content { get; set; }
        public int css_position { get; set; }
        public int css_added_to { get; set; }
        public string css_app { get; set; }
        public int css_app_hide { get; set; }
        public string css_attributes { get; set; }
        public string css_modules { get; set; }
        public int css_removed { get; set; }
        public string css_master_key { get; set; }
        public string css_path { get; set; }
        public string css_name { get; set; }
        public string css_version { get; set; }
        public Nullable<byte> css_hidden { get; set; }
        public Nullable<int> css_user_edited { get; set; }
        public Nullable<decimal> css_plugin { get; set; }
        public string css_unique_key { get; set; }
    }
}
