//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_validating
    {
        public string vid { get; set; }
        public decimal member_id { get; set; }
        public int entry_date { get; set; }
        public bool coppa_user { get; set; }
        public bool lost_pass { get; set; }
        public bool new_reg { get; set; }
        public bool email_chg { get; set; }
        public string ip_address { get; set; }
        public bool user_verified { get; set; }
        public string prev_email { get; set; }
        public sbyte spam_flag { get; set; }
        public Nullable<int> email_sent { get; set; }
        public bool forgot_security { get; set; }
        public bool do_not_delete { get; set; }
    }
}
