//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_attachments_map
    {
        public long attachment_id { get; set; }
        public string location_key { get; set; }
        public Nullable<decimal> id1 { get; set; }
        public Nullable<decimal> id2 { get; set; }
        public string temp { get; set; }
        public string id3 { get; set; }
    }
}
