//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_tags
    {
        public long tag_id { get; set; }
        public string tag_aai_lookup { get; set; }
        public string tag_aap_lookup { get; set; }
        public string tag_meta_app { get; set; }
        public string tag_meta_area { get; set; }
        public int tag_meta_id { get; set; }
        public int tag_meta_parent_id { get; set; }
        public long tag_member_id { get; set; }
        public int tag_added { get; set; }
        public int tag_prefix { get; set; }
        public string tag_text { get; set; }
    }
}
