//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_security_answers
    {
        public decimal answer_question_id { get; set; }
        public decimal answer_member_id { get; set; }
        public string answer_answer { get; set; }
        public bool answer_is_chosen { get; set; }
    }
}
