//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_streams
    {
        public decimal id { get; set; }
        public string classes { get; set; }
        public string containers { get; set; }
        public string ownership { get; set; }
        public string read { get; set; }
        public string follow { get; set; }
        public string date_type { get; set; }
        public Nullable<int> date_start { get; set; }
        public Nullable<int> date_end { get; set; }
        public int position { get; set; }
        public Nullable<long> member { get; set; }
        public string sort { get; set; }
        public Nullable<long> date_relative_days { get; set; }
        public string custom_members { get; set; }
        public string tags { get; set; }
        public string followed_types { get; set; }
        public bool include_comments { get; set; }
        public string title { get; set; }
        public bool @default { get; set; }
        public bool unread_links { get; set; }
        public string default_view { get; set; }
    }
}
