//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_themes
    {
        public int set_id { get; set; }
        public string set_name { get; set; }
        public string set_key { get; set; }
        public int set_parent_id { get; set; }
        public string set_parent_array { get; set; }
        public string set_child_array { get; set; }
        public string set_permissions { get; set; }
        public int set_is_default { get; set; }
        public string set_author_name { get; set; }
        public string set_author_url { get; set; }
        public string set_emo_dir { get; set; }
        public int set_added { get; set; }
        public int set_updated { get; set; }
        public int set_hide_from_list { get; set; }
        public int set_order { get; set; }
        public int set_by_skin_gen { get; set; }
        public string set_skin_gen_data { get; set; }
        public string set_template_settings { get; set; }
        public string set_editor_skin { get; set; }
        public string set_logo_data { get; set; }
        public string set_version { get; set; }
        public Nullable<long> set_long_version { get; set; }
        public string set_update_check { get; set; }
        public Nullable<long> set_update_last_check { get; set; }
        public string set_update_data { get; set; }
        public string set_css_map { get; set; }
        public string set_resource_map { get; set; }
        public bool set_is_acp_default { get; set; }
        public string set_cache_key { get; set; }
    }
}
