//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_hooks
    {
        public decimal id { get; set; }
        public Nullable<decimal> plugin { get; set; }
        public string app { get; set; }
        public string type { get; set; }
        public string @class { get; set; }
        public string filename { get; set; }
    }
}
