//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_plugins
    {
        public decimal plugin_id { get; set; }
        public string plugin_name { get; set; }
        public string plugin_update_check { get; set; }
        public string plugin_author { get; set; }
        public string plugin_website { get; set; }
        public string plugin_location { get; set; }
        public int plugin_version_long { get; set; }
        public string plugin_version_human { get; set; }
        public Nullable<int> plugin_update_check_last { get; set; }
        public string plugin_update_check_data { get; set; }
        public byte[] plugin_enabled { get; set; }
        public decimal plugin_order { get; set; }
        public string plugin_diagnostic_url { get; set; }
    }
}
