//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_members_warn_logs
    {
        public long wl_id { get; set; }
        public Nullable<decimal> wl_member { get; set; }
        public Nullable<decimal> wl_moderator { get; set; }
        public Nullable<int> wl_date { get; set; }
        public Nullable<int> wl_reason { get; set; }
        public Nullable<int> wl_points { get; set; }
        public string wl_note_member { get; set; }
        public string wl_note_mods { get; set; }
        public string wl_mq { get; set; }
        public string wl_rpa { get; set; }
        public string wl_suspend { get; set; }
        public Nullable<bool> wl_acknowledged { get; set; }
        public string wl_content_app { get; set; }
        public string wl_content_id1 { get; set; }
        public string wl_content_id2 { get; set; }
        public Nullable<int> wl_expire_date { get; set; }
        public string wl_content_module { get; set; }
    }
}
