//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_tasks
    {
        public decimal id { get; set; }
        public string app { get; set; }
        public string key { get; set; }
        public string frequency { get; set; }
        public decimal next_run { get; set; }
        public bool running { get; set; }
        public bool enabled { get; set; }
        public Nullable<long> plugin { get; set; }
        public bool lock_count { get; set; }
        public decimal last_run { get; set; }
    }
}
