//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_member_ranks
    {
        public short id { get; set; }
        public Nullable<int> posts { get; set; }
        public string title { get; set; }
        public string pips { get; set; }
        public string icon { get; set; }
        public bool use_icon { get; set; }
    }
}
