//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_reputation_index
    {
        public decimal id { get; set; }
        public decimal member_id { get; set; }
        public string app { get; set; }
        public string type { get; set; }
        public long type_id { get; set; }
        public long rep_date { get; set; }
        public bool rep_rating { get; set; }
        public decimal member_received { get; set; }
        public string rep_class { get; set; }
        public long item_id { get; set; }
        public string class_type_id_hash { get; set; }
    }
}
