//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_sys_conf_settings
    {
        public int conf_id { get; set; }
        public string conf_key { get; set; }
        public string conf_value { get; set; }
        public string conf_default { get; set; }
        public string conf_keywords { get; set; }
        public string conf_app { get; set; }
        public Nullable<decimal> conf_plugin { get; set; }
    }
}
