//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_admin_login_logs
    {
        public int admin_id { get; set; }
        public string admin_ip_address { get; set; }
        public string admin_username { get; set; }
        public long admin_time { get; set; }
        public long admin_success { get; set; }
        public string admin_request { get; set; }
    }
}
