//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_theme_content_history
    {
        public int content_id { get; set; }
        public int content_set_id { get; set; }
        public string content_type { get; set; }
        public string content_app { get; set; }
        public string content_location { get; set; }
        public string content_path { get; set; }
        public string content_name { get; set; }
        public string content_data { get; set; }
        public string content_content { get; set; }
        public int content_long_version { get; set; }
        public int content_date { get; set; }
    }
}
