//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_seo_meta
    {
        public int meta_id { get; set; }
        public string meta_url { get; set; }
        public string meta_tags { get; set; }
        public string meta_title { get; set; }
    }
}
