//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_rss_export
    {
        public decimal rss_id { get; set; }
        public bool rss_enabled { get; set; }
        public string rss_seo_title { get; set; }
        public string rss_configuration { get; set; }
        public Nullable<int> rss_count { get; set; }
        public int rss_position { get; set; }
        public string rss_groups { get; set; }
    }
}
