//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_theme_settings_fields
    {
        public int sc_id { get; set; }
        public int sc_set_id { get; set; }
        public string sc_key { get; set; }
        public string sc_type { get; set; }
        public int sc_multiple { get; set; }
        public string sc_content { get; set; }
        public Nullable<long> sc_updated { get; set; }
        public string sc_app { get; set; }
        public string sc_default { get; set; }
        public string sc_tab_key { get; set; }
        public Nullable<long> sc_show_in_vse { get; set; }
        public string sc_title { get; set; }
        public long sc_order { get; set; }
        public string sc_condition { get; set; }
    }
}
