//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_emoticons
    {
        public short id { get; set; }
        public string typed { get; set; }
        public string image { get; set; }
        public short clickable { get; set; }
        public string emo_set { get; set; }
        public int emo_position { get; set; }
        public long emo_set_position { get; set; }
        public string image_2x { get; set; }
        public short width { get; set; }
        public short height { get; set; }
    }
}
