//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_modules
    {
        public int sys_module_id { get; set; }
        public string sys_module_title { get; set; }
        public string sys_module_application { get; set; }
        public string sys_module_key { get; set; }
        public Nullable<bool> sys_module_protected { get; set; }
        public bool sys_module_visible { get; set; }
        public int sys_module_position { get; set; }
        public string sys_module_area { get; set; }
        public string sys_module_default_controller { get; set; }
        public bool sys_module_default { get; set; }
    }
}
