//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_file_logs
    {
        public long log_id { get; set; }
        public string log_type { get; set; }
        public string log_action { get; set; }
        public int log_configuration_id { get; set; }
        public string log_method { get; set; }
        public string log_filename { get; set; }
        public string log_msg { get; set; }
        public int log_date { get; set; }
        public string log_data { get; set; }
        public string log_container { get; set; }
        public string log_url { get; set; }
    }
}
