//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_members_warn_reasons
    {
        public long wr_id { get; set; }
        public string wr_name { get; set; }
        public Nullable<float> wr_points { get; set; }
        public Nullable<bool> wr_points_override { get; set; }
        public Nullable<int> wr_remove { get; set; }
        public string wr_remove_unit { get; set; }
        public Nullable<bool> wr_remove_override { get; set; }
        public Nullable<int> wr_order { get; set; }
        public string wr_notes { get; set; }
    }
}
