//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_pfields_data
    {
        public short pf_id { get; set; }
        public string pf_content { get; set; }
        public string pf_type { get; set; }
        public bool pf_not_null { get; set; }
        public bool pf_member_hide { get; set; }
        public short pf_max_input { get; set; }
        public bool pf_member_edit { get; set; }
        public short pf_position { get; set; }
        public bool pf_show_on_reg { get; set; }
        public string pf_input_format { get; set; }
        public bool pf_admin_only { get; set; }
        public string pf_format { get; set; }
        public int pf_group_id { get; set; }
        public string pf_search_type { get; set; }
        public bool pf_filtering { get; set; }
        public bool pf_multiple { get; set; }
    }
}
