//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_widget_areas
    {
        public decimal id { get; set; }
        public string app { get; set; }
        public string module { get; set; }
        public string controller { get; set; }
        public string widgets { get; set; }
        public string area { get; set; }
    }
}
