//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_javascript
    {
        public int javascript_id { get; set; }
        public string javascript_app { get; set; }
        public string javascript_location { get; set; }
        public string javascript_plugin { get; set; }
        public string javascript_path { get; set; }
        public string javascript_name { get; set; }
        public string javascript_type { get; set; }
        public string javascript_content { get; set; }
        public string javascript_version { get; set; }
        public Nullable<long> javascript_position { get; set; }
        public string javascript_key { get; set; }
    }
}
