//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_tags_perms
    {
        public string tag_perm_aai_lookup { get; set; }
        public string tag_perm_aap_lookup { get; set; }
        public string tag_perm_text { get; set; }
        public int tag_perm_visible { get; set; }
    }
}
