//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_item_markers
    {
        public string item_key { get; set; }
        public decimal item_member_id { get; set; }
        public string item_app { get; set; }
        public string item_read_array { get; set; }
        public int item_global_reset { get; set; }
        public int item_app_key_1 { get; set; }
        public int item_app_key_2 { get; set; }
        public int item_app_key_3 { get; set; }
    }
}
