//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_bulk_mail
    {
        public int mail_id { get; set; }
        public string mail_subject { get; set; }
        public string mail_content { get; set; }
        public string mail_opts { get; set; }
        public int mail_start { get; set; }
        public int mail_updated { get; set; }
        public int mail_sentto { get; set; }
        public bool mail_active { get; set; }
        public long mail_offset { get; set; }
    }
}
