//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_sys_cp_sessions
    {
        public string session_id { get; set; }
        public string session_ip_address { get; set; }
        public string session_member_name { get; set; }
        public decimal session_member_id { get; set; }
        public string session_member_login_key { get; set; }
        public string session_location { get; set; }
        public int session_log_in_time { get; set; }
        public int session_running_time { get; set; }
        public string session_url { get; set; }
        public byte[] session_app_data { get; set; }
    }
}
