//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_attachments
    {
        public int attach_id { get; set; }
        public string attach_ext { get; set; }
        public string attach_file { get; set; }
        public string attach_location { get; set; }
        public string attach_thumb_location { get; set; }
        public short attach_thumb_width { get; set; }
        public short attach_thumb_height { get; set; }
        public bool attach_is_image { get; set; }
        public int attach_hits { get; set; }
        public int attach_date { get; set; }
        public string attach_post_key { get; set; }
        public decimal attach_member_id { get; set; }
        public int attach_filesize { get; set; }
        public int attach_img_width { get; set; }
        public int attach_img_height { get; set; }
        public int attach_is_archived { get; set; }
    }
}
