//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_permission_index
    {
        public long perm_id { get; set; }
        public string app { get; set; }
        public string perm_type { get; set; }
        public long perm_type_id { get; set; }
        public string perm_view { get; set; }
        public string perm_2 { get; set; }
        public string perm_3 { get; set; }
        public string perm_4 { get; set; }
        public string perm_5 { get; set; }
        public string perm_6 { get; set; }
        public string perm_7 { get; set; }
        public bool owner_only { get; set; }
        public bool friend_only { get; set; }
        public string authorized_users { get; set; }
    }
}
