//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_theme_templates
    {
        public int template_id { get; set; }
        public int template_set_id { get; set; }
        public string template_group { get; set; }
        public string template_content { get; set; }
        public string template_name { get; set; }
        public string template_data { get; set; }
        public int template_updated { get; set; }
        public int template_removable { get; set; }
        public int template_added_to { get; set; }
        public int template_user_added { get; set; }
        public int template_user_edited { get; set; }
        public string template_master_key { get; set; }
        public string template_location { get; set; }
        public string template_app { get; set; }
        public string template_version { get; set; }
        public Nullable<decimal> template_plugin { get; set; }
        public string template_unique_key { get; set; }
    }
}
