//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_files_temp
    {
        public decimal id { get; set; }
        public string upload_key { get; set; }
        public string filename { get; set; }
        public string mime { get; set; }
        public string contents { get; set; }
        public long time { get; set; }
        public string storage_extension { get; set; }
    }
}
