//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_banfilters
    {
        public int ban_id { get; set; }
        public string ban_type { get; set; }
        public string ban_content { get; set; }
        public int ban_date { get; set; }
        public string ban_reason { get; set; }
    }
}
