//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_sys_lang_words
    {
        public long word_id { get; set; }
        public int lang_id { get; set; }
        public string word_app { get; set; }
        public Nullable<long> word_plugin { get; set; }
        public Nullable<int> word_theme { get; set; }
        public string word_key { get; set; }
        public string word_default { get; set; }
        public string word_custom { get; set; }
        public string word_default_version { get; set; }
        public string word_custom_version { get; set; }
        public bool word_js { get; set; }
        public bool word_export { get; set; }
    }
}
