//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_ipsconnect_slaves
    {
        public decimal slave_id { get; set; }
        public string slave_url { get; set; }
        public Nullable<int> slave_last_access { get; set; }
        public string slave_key { get; set; }
        public sbyte slave_enabled { get; set; }
    }
}
