//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_login_handlers
    {
        public string login_key { get; set; }
        public bool login_enabled { get; set; }
        public string login_settings { get; set; }
        public Nullable<int> login_order { get; set; }
        public bool login_acp { get; set; }
    }
}
