//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_profanity_filters
    {
        public int wid { get; set; }
        public string type { get; set; }
        public string swop { get; set; }
        public Nullable<bool> m_exact { get; set; }
        public string action { get; set; }
    }
}
