//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_reputation_leaderboard_history
    {
        public int leader_date { get; set; }
        public decimal leader_member_id { get; set; }
        public int leader_position { get; set; }
        public int leader_rep_total { get; set; }
    }
}
