//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_email_templates
    {
        public decimal template_id { get; set; }
        public string template_app { get; set; }
        public string template_name { get; set; }
        public string template_content_html { get; set; }
        public long template_parent { get; set; }
        public string template_data { get; set; }
        public string template_key { get; set; }
        public string template_content_plaintext { get; set; }
        public Nullable<bool> template_edited { get; set; }
    }
}
