//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_applications
    {
        public int app_id { get; set; }
        public string app_author { get; set; }
        public string app_version { get; set; }
        public int app_long_version { get; set; }
        public string app_directory { get; set; }
        public int app_added { get; set; }
        public int app_position { get; set; }
        public int app_protected { get; set; }
        public int app_enabled { get; set; }
        public bool app_hide_tab { get; set; }
        public string app_website { get; set; }
        public string app_update_check { get; set; }
        public long app_update_last_check { get; set; }
        public string app_update_version { get; set; }
        public string app_disabled_groups { get; set; }
        public string app_disabled_message { get; set; }
        public string app_diagnostic_url { get; set; }
        public Nullable<bool> app_default { get; set; }
    }
}
