//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_ignored_users
    {
        public int ignore_id { get; set; }
        public int ignore_owner_id { get; set; }
        public int ignore_ignore_id { get; set; }
        public int ignore_messages { get; set; }
        public int ignore_topics { get; set; }
        public int ignore_signatures { get; set; }
        public int ignore_chats { get; set; }
        public bool ignore_mentions { get; set; }
    }
}
