//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_spam_service_log
    {
        public long id { get; set; }
        public long log_date { get; set; }
        public int log_code { get; set; }
        public string log_msg { get; set; }
        public string email_address { get; set; }
        public string ip_address { get; set; }
    }
}
