//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_rc_reports
    {
        public int id { get; set; }
        public int rid { get; set; }
        public string report { get; set; }
        public decimal report_by { get; set; }
        public int date_reported { get; set; }
        public string ip_address { get; set; }
    }
}
