//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_polls
    {
        public int pid { get; set; }
        public Nullable<int> start_date { get; set; }
        public string choices { get; set; }
        public decimal starter_id { get; set; }
        public int votes { get; set; }
        public string poll_question { get; set; }
        public bool poll_only { get; set; }
        public int poll_view_voters { get; set; }
        public long poll_closed { get; set; }
    }
}
