//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_theme_resources
    {
        public int resource_id { get; set; }
        public int resource_set_id { get; set; }
        public string resource_app { get; set; }
        public string resource_location { get; set; }
        public string resource_path { get; set; }
        public string resource_name { get; set; }
        public int resource_added { get; set; }
        public string resource_filename { get; set; }
        public Nullable<decimal> resource_plugin { get; set; }
        public byte[] resource_data { get; set; }
        public bool resource_user_edited { get; set; }
    }
}
