//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_share_links
    {
        public long share_id { get; set; }
        public string share_title { get; set; }
        public string share_key { get; set; }
        public int share_enabled { get; set; }
        public int share_position { get; set; }
        public int share_canonical { get; set; }
        public string share_groups { get; set; }
        public byte share_autoshare { get; set; }
    }
}
