//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_files
    {
        public decimal id { get; set; }
        public string filename { get; set; }
        public string salt { get; set; }
        public byte[] contents { get; set; }
        public string container { get; set; }
    }
}
