//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_sessions
    {
        public string id { get; set; }
        public string member_name { get; set; }
        public string seo_name { get; set; }
        public Nullable<decimal> member_id { get; set; }
        public string ip_address { get; set; }
        public string browser { get; set; }
        public Nullable<int> running_time { get; set; }
        public Nullable<bool> login_type { get; set; }
        public Nullable<short> member_group { get; set; }
        public bool in_error { get; set; }
        public string current_appcomponent { get; set; }
        public string current_module { get; set; }
        public string current_controller { get; set; }
        public string uagent_key { get; set; }
        public string uagent_version { get; set; }
        public string uagent_type { get; set; }
        public int search_thread_id { get; set; }
        public int search_thread_time { get; set; }
        public byte[] data { get; set; }
        public string location_url { get; set; }
        public string location_lang { get; set; }
        public string location_data { get; set; }
        public string location_permissions { get; set; }
        public Nullable<long> current_id { get; set; }
        public long theme_id { get; set; }
    }
}
