//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_member_status_updates
    {
        public int status_id { get; set; }
        public decimal status_member_id { get; set; }
        public long status_date { get; set; }
        public string status_content { get; set; }
        public long status_replies { get; set; }
        public string status_last_ids { get; set; }
        public int status_is_latest { get; set; }
        public int status_is_locked { get; set; }
        public string status_hash { get; set; }
        public int status_imported { get; set; }
        public int status_author_id { get; set; }
        public string status_author_ip { get; set; }
        public int status_approved { get; set; }
    }
}
