//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_rc_comments
    {
        public int id { get; set; }
        public int rid { get; set; }
        public string comment { get; set; }
        public decimal comment_by { get; set; }
        public int comment_date { get; set; }
        public sbyte approved { get; set; }
        public int edit_date { get; set; }
        public string author_name { get; set; }
        public string ip_address { get; set; }
    }
}
