//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class forums_archive_rules
    {
        public string archive_key { get; set; }
        public string archive_app { get; set; }
        public string archive_field { get; set; }
        public string archive_value { get; set; }
        public string archive_text { get; set; }
        public string archive_unit { get; set; }
        public int archive_skip { get; set; }
    }
}
