//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class forums_rss_import
    {
        public int rss_import_id { get; set; }
        public bool rss_import_enabled { get; set; }
        public string rss_import_title { get; set; }
        public string rss_import_url { get; set; }
        public int rss_import_forum_id { get; set; }
        public decimal rss_import_mid { get; set; }
        public short rss_import_pergo { get; set; }
        public short rss_import_time { get; set; }
        public int rss_import_last_import { get; set; }
        public string rss_import_showlink { get; set; }
        public bool rss_import_topic_open { get; set; }
        public bool rss_import_topic_hide { get; set; }
        public string rss_import_topic_pre { get; set; }
        public bool rss_import_allow_html { get; set; }
        public bool rss_import_auth { get; set; }
        public string rss_import_auth_user { get; set; }
        public string rss_import_auth_pass { get; set; }
    }
}
