//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class forums_answer_ratings
    {
        public decimal id { get; set; }
        public long post { get; set; }
        public decimal member { get; set; }
        public bool rating { get; set; }
        public long date { get; set; }
        public Nullable<long> topic { get; set; }
    }
}
