//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class forums_topic_mmod
    {
        public short mm_id { get; set; }
        public bool mm_enabled { get; set; }
        public string topic_state { get; set; }
        public string topic_pin { get; set; }
        public short topic_move { get; set; }
        public bool topic_move_link { get; set; }
        public string topic_title_st { get; set; }
        public string topic_title_end { get; set; }
        public bool topic_reply { get; set; }
        public string topic_reply_content { get; set; }
        public bool topic_reply_postcount { get; set; }
        public string mm_forums { get; set; }
        public bool topic_approve { get; set; }
    }
}
