//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class forums_forums
    {
        public short id { get; set; }
        public int topics { get; set; }
        public int posts { get; set; }
        public Nullable<int> last_post { get; set; }
        public decimal last_poster_id { get; set; }
        public string last_poster_name { get; set; }
        public Nullable<long> position { get; set; }
        public string password { get; set; }
        public string password_override { get; set; }
        public string last_title { get; set; }
        public Nullable<int> last_id { get; set; }
        public string sort_key { get; set; }
        public Nullable<bool> show_rules { get; set; }
        public Nullable<bool> preview_posts { get; set; }
        public bool allow_poll { get; set; }
        public bool inc_postcount { get; set; }
        public Nullable<int> skin_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string redirect_url { get; set; }
        public bool redirect_on { get; set; }
        public int redirect_hits { get; set; }
        public Nullable<bool> sub_can_post { get; set; }
        public bool permission_showtopic { get; set; }
        public int queued_topics { get; set; }
        public int queued_posts { get; set; }
        public bool forum_allow_rating { get; set; }
        public long min_posts_post { get; set; }
        public long min_posts_view { get; set; }
        public bool can_view_others { get; set; }
        public string name_seo { get; set; }
        public string seo_last_title { get; set; }
        public string seo_last_name { get; set; }
        public string last_x_topic_ids { get; set; }
        public long forums_bitoptions { get; set; }
        public int disable_sharelinks { get; set; }
        public string tag_predefined { get; set; }
        public int archived_topics { get; set; }
        public int archived_posts { get; set; }
        public string ipseo_priority { get; set; }
        public bool viglink { get; set; }
        public string qa_rate_questions { get; set; }
        public string qa_rate_answers { get; set; }
        public string icon { get; set; }
        public Nullable<long> conv_parent { get; set; }
    }
}
