//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class forums_archive_posts
    {
        public int archive_id { get; set; }
        public int archive_author_id { get; set; }
        public string archive_author_name { get; set; }
        public string archive_ip_address { get; set; }
        public int archive_content_date { get; set; }
        public string archive_content { get; set; }
        public int archive_queued { get; set; }
        public int archive_topic_id { get; set; }
        public int archive_is_first { get; set; }
        public long archive_bwoptions { get; set; }
        public string archive_attach_key { get; set; }
        public int archive_html_mode { get; set; }
        public int archive_show_edited_by { get; set; }
        public int archive_edit_time { get; set; }
        public string archive_edit_name { get; set; }
        public string archive_edit_reason { get; set; }
        public int archive_added { get; set; }
        public int archive_restored { get; set; }
        public int archive_forum_id { get; set; }
        public Nullable<int> archive_field_int { get; set; }
    }
}
