//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class forums_posts
    {
        public int pid { get; set; }
        public Nullable<bool> append_edit { get; set; }
        public Nullable<int> edit_time { get; set; }
        public decimal author_id { get; set; }
        public string author_name { get; set; }
        public string ip_address { get; set; }
        public Nullable<int> post_date { get; set; }
        public string post { get; set; }
        public bool queued { get; set; }
        public int topic_id { get; set; }
        public Nullable<bool> new_topic { get; set; }
        public string edit_name { get; set; }
        public string post_key { get; set; }
        public short post_htmlstate { get; set; }
        public string post_edit_reason { get; set; }
        public long post_bwoptions { get; set; }
        public int pdelete_time { get; set; }
        public Nullable<int> post_field_int { get; set; }
        public string post_field_t1 { get; set; }
        public string post_field_t2 { get; set; }
    }
}
