//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_packages_hosting
    {
        public int p_id { get; set; }
        public Nullable<int> p_queue { get; set; }
        public Nullable<int> p_quota { get; set; }
        public Nullable<bool> p_ip { get; set; }
        public Nullable<bool> p_cgi { get; set; }
        public Nullable<bool> p_frontpage { get; set; }
        public Nullable<bool> p_hasshell { get; set; }
        public Nullable<int> p_maxftp { get; set; }
        public Nullable<int> p_maxsql { get; set; }
        public Nullable<int> p_maxpop { get; set; }
        public Nullable<int> p_maxlst { get; set; }
        public Nullable<int> p_maxsub { get; set; }
        public Nullable<int> p_maxpark { get; set; }
        public Nullable<int> p_maxaddon { get; set; }
        public Nullable<int> p_bwlimit { get; set; }
    }
}
