//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_referral_rules
    {
        public long rrule_id { get; set; }
        public string rrule_name { get; set; }
        public string rrule_by_purchases_type { get; set; }
        public string rrule_by_purchases_op { get; set; }
        public string rrule_by_purchases_unit { get; set; }
        public string rrule_by_group { get; set; }
        public string rrule_for_purchases_type { get; set; }
        public string rrule_for_purchases_op { get; set; }
        public string rrule_for_purchases_unit { get; set; }
        public string rrule_for_group { get; set; }
        public string rrule_purchase_packages { get; set; }
        public Nullable<bool> rrule_purchase_any { get; set; }
        public Nullable<bool> rrule_purchase_package_limit { get; set; }
        public Nullable<bool> rrule_purchase_renewal { get; set; }
        public string rrule_purchase_amount_op { get; set; }
        public string rrule_purchase_amount_unit { get; set; }
        public Nullable<int> rrule_commission { get; set; }
        public string rrule_commission_limit { get; set; }
    }
}
