//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_customer_history
    {
        public int log_id { get; set; }
        public decimal log_member { get; set; }
        public Nullable<decimal> log_by { get; set; }
        public string log_type { get; set; }
        public string log_data { get; set; }
        public double log_date { get; set; }
        public string log_ip_address { get; set; }
    }
}
