//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_cart_uploads
    {
        public decimal id { get; set; }
        public string session_id { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<long> item_id { get; set; }
    }
}
