//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_streams
    {
        public decimal stream_id { get; set; }
        public string stream_departments { get; set; }
        public string stream_statuses { get; set; }
        public string stream_severities { get; set; }
        public string stream_staff { get; set; }
        public string stream_from_email { get; set; }
        public string stream_search_term { get; set; }
        public Nullable<long> stream_started { get; set; }
        public Nullable<long> stream_last_reply { get; set; }
        public Nullable<long> stream_last_staff_reply { get; set; }
        public Nullable<decimal> stream_owner { get; set; }
        public Nullable<int> stream_position { get; set; }
        public Nullable<long> stream_last_new_reply { get; set; }
        public bool stream_tracked { get; set; }
        public string stream_title { get; set; }
        public bool stream_temporary { get; set; }
    }
}
