//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_reviews
    {
        public int review_id { get; set; }
        public int review_product { get; set; }
        public Nullable<decimal> review_author_id { get; set; }
        public string review_author_name { get; set; }
        public string review_ip_address { get; set; }
        public Nullable<int> review_date { get; set; }
        public Nullable<int> review_edit_date { get; set; }
        public Nullable<int> review_approved { get; set; }
        public string review_text { get; set; }
        public Nullable<short> review_rating { get; set; }
        public Nullable<int> review_useful { get; set; }
        public Nullable<int> review_votes { get; set; }
        public bool review_edit_show { get; set; }
        public string review_edit_member_name { get; set; }
        public string review_edit_reason { get; set; }
        public Nullable<decimal> review_edit_member_id { get; set; }
        public string review_vote_data { get; set; }
    }
}
