//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_package_fields
    {
        public int cf_id { get; set; }
        public string cf_name { get; set; }
        public string cf_desc { get; set; }
        public string cf_type { get; set; }
        public string cf_extra { get; set; }
        public string cf_packages { get; set; }
        public int cf_position { get; set; }
        public bool cf_sticky { get; set; }
        public bool cf_purchase { get; set; }
        public bool cf_required { get; set; }
        public bool cf_editable { get; set; }
        public bool cf_multiple { get; set; }
        public bool cf_invoice { get; set; }
    }
}
