//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_ship_orders
    {
        public int o_id { get; set; }
        public int o_invoice { get; set; }
        public string o_data { get; set; }
        public string o_status { get; set; }
        public int o_method { get; set; }
        public string o_items { get; set; }
        public int o_date { get; set; }
        public int o_shipped_date { get; set; }
        public string o_service { get; set; }
        public string o_tracknumber { get; set; }
        public string o_api { get; set; }
        public string o_api_service { get; set; }
        public string o_label { get; set; }
        public string o_extra { get; set; }
    }
}
