//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_paymethods
    {
        public int m_id { get; set; }
        public string m_gateway { get; set; }
        public string m_settings { get; set; }
        public bool m_active { get; set; }
        public int m_position { get; set; }
        public string m_countries { get; set; }
    }
}
