//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_packages
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_seo_name { get; set; }
        public int p_group { get; set; }
        public int p_stock { get; set; }
        public bool p_reg { get; set; }
        public bool p_store { get; set; }
        public string p_member_groups { get; set; }
        public bool p_allow_upgrading { get; set; }
        public bool p_upgrade_charge { get; set; }
        public bool p_allow_downgrading { get; set; }
        public bool p_downgrade_refund { get; set; }
        public string p_base_price { get; set; }
        public int p_tax { get; set; }
        public int p_renewal_days { get; set; }
        public int p_primary_group { get; set; }
        public string p_secondary_group { get; set; }
        public sbyte p_return_primary { get; set; }
        public sbyte p_return_secondary { get; set; }
        public int p_position { get; set; }
        public string p_associable { get; set; }
        public bool p_force_assoc { get; set; }
        public string p_assoc_error { get; set; }
        public string p_discounts { get; set; }
        public string p_page { get; set; }
        public bool p_support { get; set; }
        public int p_support_department { get; set; }
        public Nullable<int> p_support_severity { get; set; }
        public bool p_featured { get; set; }
        public bool p_upsell { get; set; }
        public string p_notify { get; set; }
        public string p_type { get; set; }
        public int p_custom { get; set; }
        public bool p_reviewable { get; set; }
        public bool p_review_moderate { get; set; }
        public string p_image { get; set; }
        public string p_methods { get; set; }
        public string p_renew_options { get; set; }
        public bool p_group_renewals { get; set; }
        public bool p_rebuild_thumb { get; set; }
        public Nullable<int> p_renewal_days_advance { get; set; }
        public long p_date_added { get; set; }
        public int p_reviews { get; set; }
        public float p_rating { get; set; }
        public Nullable<long> p_unapproved_reviews { get; set; }
        public Nullable<long> p_hidden_reviews { get; set; }
        public Nullable<long> p_grace_period { get; set; }
        public Nullable<long> p_conv_associable { get; set; }
    }
}
