//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_fraud_rules
    {
        public long f_id { get; set; }
        public string f_name { get; set; }
        public string f_groups { get; set; }
        public string f_amount { get; set; }
        public string f_amount_unit { get; set; }
        public string f_methods { get; set; }
        public Nullable<bool> f_voucher { get; set; }
        public string f_email { get; set; }
        public string f_email_unit { get; set; }
        public string f_country { get; set; }
        public string f_maxmind { get; set; }
        public Nullable<decimal> f_maxmind_unit { get; set; }
        public Nullable<bool> f_maxmind_address_valid { get; set; }
        public Nullable<bool> f_maxmind_address_match { get; set; }
        public string f_maxmind_proxy { get; set; }
        public Nullable<decimal> f_maxmind_proxy_unit { get; set; }
        public Nullable<bool> f_maxmind_freeemail { get; set; }
        public Nullable<bool> f_maxmind_phone_match { get; set; }
        public Nullable<bool> f_maxmind_riskyemail { get; set; }
        public string f_trans_okay { get; set; }
        public Nullable<int> f_trans_okay_unit { get; set; }
        public string f_trans_fraud { get; set; }
        public Nullable<int> f_trans_fraud_unit { get; set; }
        public string f_action { get; set; }
        public Nullable<bool> f_action_ban { get; set; }
        public Nullable<int> f_order { get; set; }
        public Nullable<bool> f_coupon { get; set; }
    }
}
