//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_package_images
    {
        public long image_id { get; set; }
        public Nullable<int> image_product { get; set; }
        public string image_location { get; set; }
        public Nullable<bool> image_primary { get; set; }
        public string image_temp { get; set; }
    }
}
