//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_transactions
    {
        public int t_id { get; set; }
        public decimal t_member { get; set; }
        public int t_invoice { get; set; }
        public int t_method { get; set; }
        public string t_status { get; set; }
        public decimal t_amount { get; set; }
        public int t_date { get; set; }
        public string t_extra { get; set; }
        public string t_fraud { get; set; }
        public string t_gw_id { get; set; }
        public string t_ip { get; set; }
        public int t_fraud_blocked { get; set; }
        public string t_currency { get; set; }
        public Nullable<int> t_auth { get; set; }
        public Nullable<decimal> t_billing_agreement { get; set; }
    }
}
