//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_stock_actions
    {
        public int action_id { get; set; }
        public string action_name { get; set; }
        public int action_department { get; set; }
        public int action_status { get; set; }
        public decimal action_staff { get; set; }
        public string action_message { get; set; }
        public int action_position { get; set; }
        public string action_show_in { get; set; }
    }
}
