//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_hosting_accounts
    {
        public int ps_id { get; set; }
        public Nullable<int> account_server { get; set; }
        public string account_domain { get; set; }
        public string account_username { get; set; }
        public string account_password { get; set; }
        public Nullable<bool> account_exists { get; set; }
    }
}
