//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_purchases
    {
        public int ps_id { get; set; }
        public decimal ps_member { get; set; }
        public string ps_name { get; set; }
        public bool ps_active { get; set; }
        public bool ps_cancelled { get; set; }
        public int ps_start { get; set; }
        public int ps_expire { get; set; }
        public int ps_renewals { get; set; }
        public decimal ps_renewal_price { get; set; }
        public string ps_renewal_unit { get; set; }
        public string ps_app { get; set; }
        public string ps_type { get; set; }
        public int ps_item_id { get; set; }
        public string ps_item_uri { get; set; }
        public string ps_admin_uri { get; set; }
        public string ps_custom_fields { get; set; }
        public string ps_extra { get; set; }
        public int ps_parent { get; set; }
        public int ps_invoice_pending { get; set; }
        public bool ps_invoice_warning_sent { get; set; }
        public Nullable<decimal> ps_pay_to { get; set; }
        public Nullable<int> ps_commission { get; set; }
        public int ps_original_invoice { get; set; }
        public int ps_tax { get; set; }
        public bool ps_can_reactivate { get; set; }
        public string ps_grouped_renewals { get; set; }
        public string ps_renewal_currency { get; set; }
        public bool ps_show { get; set; }
        public long ps_grace_period { get; set; }
        public Nullable<decimal> ps_billing_agreement { get; set; }
        public Nullable<long> ps_conv_parent { get; set; }
    }
}
