//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_departments
    {
        public int dpt_id { get; set; }
        public string dpt_name { get; set; }
        public bool dpt_open { get; set; }
        public bool dpt_require_package { get; set; }
        public string dpt_packages { get; set; }
        public int dpt_position { get; set; }
        public string dpt_email { get; set; }
        public string dpt_notify { get; set; }
        public bool dpt_notify_reply { get; set; }
        public string dpt_ppi { get; set; }
        public string dpt_staff { get; set; }
        public Nullable<long> dpt_ppi_tax { get; set; }
    }
}
