//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_hosting_errors
    {
        public int e_id { get; set; }
        public Nullable<int> e_time { get; set; }
        public Nullable<int> e_server { get; set; }
        public string e_message { get; set; }
        public string e_extra { get; set; }
    }
}
