//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_replies
    {
        public int reply_id { get; set; }
        public int reply_request { get; set; }
        public decimal reply_member { get; set; }
        public string reply_type { get; set; }
        public string reply_post { get; set; }
        public bool reply_hidden { get; set; }
        public int reply_date { get; set; }
        public string reply_email { get; set; }
        public string reply_cc { get; set; }
        public string reply_raw { get; set; }
        public string reply_textformat { get; set; }
        public string reply_ip_address { get; set; }
        public string reply_bcc { get; set; }
    }
}
