//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_licensekeys
    {
        public string lkey_key { get; set; }
        public string lkey_type { get; set; }
        public string lkey_identifier { get; set; }
        public Nullable<int> lkey_purchase { get; set; }
        public Nullable<decimal> lkey_member { get; set; }
        public Nullable<bool> lkey_active { get; set; }
        public Nullable<int> lkey_uses { get; set; }
        public Nullable<int> lkey_max_uses { get; set; }
        public string lkey_activate_data { get; set; }
        public Nullable<int> lkey_generated { get; set; }
    }
}
