//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_customer_addresses
    {
        public decimal id { get; set; }
        public decimal member { get; set; }
        public string address { get; set; }
        public long primary_billing { get; set; }
        public bool primary_shipping { get; set; }
        public Nullable<long> added { get; set; }
    }
}
