//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_package_groups
    {
        public int pg_id { get; set; }
        public string pg_name { get; set; }
        public string pg_seo_name { get; set; }
        public int pg_position { get; set; }
        public int pg_parent { get; set; }
        public string pg_image { get; set; }
        public Nullable<long> pg_conv_parent { get; set; }
    }
}
