//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_product_options
    {
        public int opt_id { get; set; }
        public Nullable<int> opt_package { get; set; }
        public string opt_values { get; set; }
        public Nullable<int> opt_stock { get; set; }
        public string opt_base_price { get; set; }
        public string opt_renew_price { get; set; }
    }
}
