//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_ratings
    {
        public long rating_reply { get; set; }
        public Nullable<short> rating_rating { get; set; }
        public Nullable<decimal> rating_from { get; set; }
        public Nullable<decimal> rating_staff { get; set; }
        public string rating_note { get; set; }
        public Nullable<int> rating_date { get; set; }
    }
}
