//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_alternate_contacts
    {
        public decimal main_id { get; set; }
        public decimal alt_id { get; set; }
        public string purchases { get; set; }
        public bool billing { get; set; }
        public bool support { get; set; }
        public Nullable<long> conv_alt_id { get; set; }
    }
}
