//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_customer_fields
    {
        public int f_id { get; set; }
        public string f_column { get; set; }
        public string f_name { get; set; }
        public string f_type { get; set; }
        public string f_extra { get; set; }
        public Nullable<int> f_position { get; set; }
        public Nullable<bool> f_reg_show { get; set; }
        public Nullable<bool> f_reg_require { get; set; }
        public Nullable<bool> f_purchase_show { get; set; }
        public Nullable<bool> f_purchase_require { get; set; }
        public bool f_multiple { get; set; }
    }
}
