//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_requests
    {
        public int r_id { get; set; }
        public string r_title { get; set; }
        public decimal r_member { get; set; }
        public int r_department { get; set; }
        public int r_purchase { get; set; }
        public short r_status { get; set; }
        public Nullable<int> r_severity { get; set; }
        public bool r_severity_lock { get; set; }
        public int r_started { get; set; }
        public int r_last_reply { get; set; }
        public decimal r_last_reply_by { get; set; }
        public int r_last_new_reply { get; set; }
        public int r_last_staff_reply { get; set; }
        public decimal r_staff { get; set; }
        public bool r_staff_lock { get; set; }
        public int r_replies { get; set; }
        public string r_notify { get; set; }
        public string r_email { get; set; }
        public string r_email_key { get; set; }
        public bool r_ar_notify { get; set; }
        public string r_cfields { get; set; }
        public Nullable<long> r_ppi_invoice { get; set; }
    }
}
