//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_severities
    {
        public int sev_id { get; set; }
        public string sev_name { get; set; }
        public string sev_icon { get; set; }
        public string sev_color { get; set; }
        public Nullable<bool> sev_default { get; set; }
        public Nullable<bool> sev_public { get; set; }
        public Nullable<int> sev_position { get; set; }
        public string sev_action { get; set; }
        public string sev_departments { get; set; }
    }
}
