//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_statuses
    {
        public int status_id { get; set; }
        public string status_name { get; set; }
        public string status_public_name { get; set; }
        public string status_public_set { get; set; }
        public bool status_default_member { get; set; }
        public bool status_default_staff { get; set; }
        public bool status_is_locked { get; set; }
        public bool status_assign { get; set; }
        public int status_position { get; set; }
        public bool status_open { get; set; }
        public string status_color { get; set; }
        public bool status_log { get; set; }
    }
}
