//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_invoices
    {
        public int i_id { get; set; }
        public string i_status { get; set; }
        public string i_title { get; set; }
        public decimal i_member { get; set; }
        public string i_items { get; set; }
        public decimal i_total { get; set; }
        public int i_date { get; set; }
        public string i_return_uri { get; set; }
        public int i_paid { get; set; }
        public string i_status_extra { get; set; }
        public short i_discount { get; set; }
        public string i_renewal_ids { get; set; }
        public string i_po { get; set; }
        public string i_notes { get; set; }
        public string i_shipaddress { get; set; }
        public string i_billaddress { get; set; }
        public string i_currency { get; set; }
        public string i_guest_data { get; set; }
        public string i_billcountry { get; set; }
    }
}
