//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_views
    {
        public int view_rid { get; set; }
        public decimal view_member { get; set; }
        public Nullable<int> view_first { get; set; }
        public Nullable<int> view_last { get; set; }
        public Nullable<int> view_reply { get; set; }
    }
}
