//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_payouts
    {
        public int po_id { get; set; }
        public float po_amount { get; set; }
        public decimal po_member { get; set; }
        public string po_gateway { get; set; }
        public string po_data { get; set; }
        public string po_status { get; set; }
        public int po_date { get; set; }
        public string po_currency { get; set; }
        public Nullable<long> po_completed { get; set; }
        public string po_gw_id { get; set; }
        public string po_ip { get; set; }
        public Nullable<decimal> po_processed_by { get; set; }
    }
}
