//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_donate_logs
    {
        public long dl_id { get; set; }
        public Nullable<int> dl_goal { get; set; }
        public Nullable<decimal> dl_member { get; set; }
        public Nullable<float> dl_amount { get; set; }
        public Nullable<int> dl_invoice { get; set; }
        public Nullable<int> dl_date { get; set; }
    }
}
