//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_eom
    {
        public long eom_id { get; set; }
        public string eom_url { get; set; }
        public string eom_type { get; set; }
        public string eom_value { get; set; }
        public string eom_notify { get; set; }
    }
}
