//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_packages_products
    {
        public int p_id { get; set; }
        public bool p_physical { get; set; }
        public bool p_subscription { get; set; }
        public string p_shipping { get; set; }
        public float p_weight { get; set; }
        public string p_lkey { get; set; }
        public string p_lkey_identifier { get; set; }
        public Nullable<int> p_lkey_uses { get; set; }
        public bool p_show { get; set; }
        public Nullable<float> p_length { get; set; }
        public Nullable<float> p_width { get; set; }
        public Nullable<float> p_height { get; set; }
    }
}
