//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_shipping
    {
        public int s_id { get; set; }
        public string s_name { get; set; }
        public string s_locations { get; set; }
        public string s_type { get; set; }
        public string s_rates { get; set; }
        public int s_tax { get; set; }
        public int s_order { get; set; }
    }
}
