//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_donate_goals
    {
        public int d_id { get; set; }
        public string d_name { get; set; }
        public string d_desc { get; set; }
        public float d_goal { get; set; }
        public float d_current { get; set; }
        public int d_position { get; set; }
        public string d_currency { get; set; }
    }
}
