//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_fields
    {
        public int sf_id { get; set; }
        public string sf_name { get; set; }
        public string sf_desc { get; set; }
        public string sf_type { get; set; }
        public string sf_extra { get; set; }
        public string sf_departments { get; set; }
        public int sf_position { get; set; }
        public bool sf_required { get; set; }
        public bool sf_multiple { get; set; }
        public short sf_max_input { get; set; }
        public string sf_input_format { get; set; }
        public bool sf_validate { get; set; }
    }
}
