//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_notes
    {
        public int note_id { get; set; }
        public decimal note_member { get; set; }
        public string note_text { get; set; }
        public decimal note_author { get; set; }
        public int note_date { get; set; }
    }
}
