//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_customers
    {
        public decimal member_id { get; set; }
        public string cm_first_name { get; set; }
        public string cm_last_name { get; set; }
        public string cm_profiles { get; set; }
        public string field_1 { get; set; }
        public string cm_phone { get; set; }
    }
}
