//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_packages_ads
    {
        public int p_id { get; set; }
        public string p_locations { get; set; }
        public string p_exempt { get; set; }
        public Nullable<int> p_expire { get; set; }
        public string p_expire_unit { get; set; }
        public Nullable<int> p_max_height { get; set; }
        public Nullable<int> p_max_width { get; set; }
    }
}
