//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBotAuthenticationServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexus_support_request_log
    {
        public decimal rlog_id { get; set; }
        public long rlog_request { get; set; }
        public decimal rlog_member { get; set; }
        public string rlog_action { get; set; }
        public Nullable<int> rlog_old { get; set; }
        public Nullable<int> rlog_new { get; set; }
        public int rlog_date { get; set; }
    }
}
